import ProjectDescription

let project = Project(
    name: "Wammer",
    packages: [
        .local(path: "Vendored/CocoaAsyncSocket"),
        .local(path: "Vendored/libtelnet"),
        .local(path: "Vendored/SAMRateLimit"),
        .local(path: "Vendored/KVOController"),
        .local(path: "Vendored/OSCache"),
        .local(path: "Vendored/MyLilTimer"),
        .local(path: "Vendored/TTTAttributedLabel"),
        .local(path: "Vendored/JASidePanels"),
        .local(path: "Vendored/Masonry"),
        .local(path: "Vendored/JSQSystemSoundPlayer"),
        .local(path: "Vendored/DAKeyboardControl"),
        .local(path: "Vendored/JTSImageViewController"),
        .local(path: "Vendored/VTAcknowledgementsViewController"),
        .local(path: "Vendored/QuickDialog"),
        .local(path: "Vendored/FXForms"),
        .local(path: "Vendored/SPLCore"),
        .local(path: "Vendored/SSAccessibility"),
        .local(path: "Vendored/SSDataSources"),
        .local(path: "Vendored/SSOperations"),
        .local(path: "Vendored/SPLUserActivity"),
        .local(path: "Vendored/libextobjc"),
        .local(path: "Vendored/Expecta"),
        .local(path: "Vendored/OCMock"),
    ],
    targets: [
        .target(
            name: "Wammer",
            destinations: [.iPhone, .iPad, .macCatalyst],
            product: .app,
            bundleId: "org.ncmud.wammer",
            deploymentTargets: .iOS("26.0"),
            infoPlist: .extendingDefault(with: [
                "LSApplicationCategoryType": .string("public.app-category.games"),
                "CFBundleDisplayName": .string("MUDWammer"),
                "ITSAppUsesNonExemptEncryption": .boolean(false),
                "CFBundleShortVersionString": .string("1.0.0"),
                "CFBundleVersion": .string("1"),
                "UIAppFonts": .array([
                    .string("AndaleMono.ttf"),
                    .string("AnonymousProMinusB.ttf"),
                    .string("CourierPrimeBold.ttf"),
                    .string("FiraMono.ttf"),
                    .string("Inconsolata.otf"),
                    .string("SourceCodePro-Medium.ttf"),
                    .string("VeraMono.ttf"),
                    .string("fantasquesans.ttf"),
                    .string("larabiefont.ttf"),
                    .string("lekton.ttf"),
                    .string("luculent.ttf"),
                    .string("monkey.ttf"),
                    .string("monof55.ttf"),
                    .string("monofonto.ttf"),
                    .string("mplus-1m-regular.ttf"),
                    .string("saxmono.ttf"),
                    .string("skyhookmono.ttf"),
                    .string("spacefurs-mono.ttf"),
                    .string("unispacebd.ttf"),
                ]),
                "CFBundleURLTypes": .array([
                    .dictionary([
                        "CFBundleURLSchemes": .array([
                            .string("telnet"),
                        ]),
                    ]),
                ]),
                "UIFileSharingEnabled": .boolean(true),
                "UIViewControllerBasedStatusBarAppearance": .boolean(true),
                "UISupportedInterfaceOrientations": .array([
                    .string("UIInterfaceOrientationPortrait"),
                    .string("UIInterfaceOrientationPortraitUpsideDown"),
                    .string("UIInterfaceOrientationLandscapeLeft"),
                    .string("UIInterfaceOrientationLandscapeRight"),
                ]),
                "UILaunchStoryboardName": .string("LaunchScreen"),
                "UIApplicationSceneManifest": .dictionary([
                    "UIApplicationSupportsMultipleScenes": .boolean(true),
                    "UISceneConfigurations": .dictionary([
                        "UIWindowSceneSessionRoleApplication": .array([
                            .dictionary([
                                "UISceneConfigurationName": .string("Default Configuration"),
                                "UISceneDelegateClassName": .string("WammerSceneDelegate"),
                            ]),
                        ]),
                    ]),
                ]),
            ]),
            sources: [
                "src/Mudrammer/**",
            ],
            resources: [
                "src/Mudrammer/Supporting Files/Fonts/**",
                "src/Mudrammer/Supporting Files/Sounds/**",
                "src/Mudrammer/Supporting Files/en.lproj/**",
                "src/Mudrammer/Supporting Files/fr.lproj/**",
                "src/Mudrammer/Supporting Files/it.lproj/**",
                "src/Mudrammer/Images.xcassets",
                "src/Mudrammer/Supporting Files/LaunchScreen.storyboard",
            ],
            entitlements: "src/Mudrammer/Supporting Files/MUDRammer.entitlements",
            dependencies: [
                .package(product: "CocoaAsyncSocket"),
                .package(product: "libtelnet"),
                .package(product: "SAMRateLimit"),
                .package(product: "KVOController"),
                .package(product: "OSCache"),
                .package(product: "MyLilTimer"),
                .package(product: "TTTAttributedLabel"),
                .package(product: "JASidePanels"),
                .package(product: "Masonry"),
                .package(product: "JSQSystemSoundPlayer"),
                .package(product: "DAKeyboardControl"),
                .package(product: "JTSImageViewController"),
                .package(product: "VTAcknowledgementsViewController"),
                .package(product: "QuickDialog"),
                .package(product: "FXForms"),
                .package(product: "SPLCore"),
                .package(product: "SSAccessibility"),
                .package(product: "SSDataSources"),
                .package(product: "SSOperations"),
                .package(product: "SPLUserActivity"),
                .package(product: "libextobjc"),
                .sdk(name: "QuartzCore", type: .framework),
                .sdk(name: "CoreText", type: .framework),
                .sdk(name: "CFNetwork", type: .framework),
                .sdk(name: "Security", type: .framework),
                .sdk(name: "UserNotifications", type: .framework),
                .sdk(name: "z", type: .library),
            ],
            settings: .settings(
                base: [
                    "DEVELOPMENT_TEAM": "H3R5ZX3287",
                    "CODE_SIGN_IDENTITY[sdk=macosx*]": "Apple Development",
                    "CLANG_ENABLE_MODULES": "YES",
                    "DEFINES_MODULE": "YES",
                    "SWIFT_INSTALL_OBJC_HEADER": "YES",
                    "SWIFT_OBJC_INTERFACE_HEADER_NAME": "Wammer-Swift.h",
                    "SWIFT_ENABLE_EXPLICIT_MODULES": "NO",
                    "DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER": "NO",
                    "HEADER_SEARCH_PATHS": .array([
                        "$(SRCROOT)/Vendored/**",
                        "$(SRCROOT)/src/Mudrammer/**",
                    ]),
                    "GCC_PREFIX_HEADER": "$(SRCROOT)/src/Mudrammer/Supporting Files/Mudrammer-Prefix.pch",
                    "SWIFT_OBJC_BRIDGING_HEADER": "$(SRCROOT)/src/Mudrammer/Supporting Files/Wammer-Bridging-Header.h",
                    "ENABLE_MODULE_VERIFIER": "YES",
                    "ENABLE_USER_SCRIPT_SANDBOXING": "YES",
                ]
            )
        ),
        .target(
            name: "MRTests",
            destinations: .iOS,
            product: .unitTests,
            bundleId: "org.ncmud.wammer.tests",
            infoPlist: "src/MRTests/MRTests-Info.plist",
            sources: [
                "src/MRTests/**",
            ],
            dependencies: [
                .target(name: "Wammer"),
                .package(product: "Expecta"),
                .package(product: "OCMock"),
            ],
            settings: .settings(
                base: [
                    "CLANG_ENABLE_MODULES": "YES",
                    "HEADER_SEARCH_PATHS": .array([
                        "$(SRCROOT)/Vendored/**",
                        "$(SRCROOT)/src/Mudrammer/**",
                        "$(TARGET_TEMP_DIR)/../Wammer.build/DerivedSources",
                    ]),
                    "GCC_PREFIX_HEADER": "$(SRCROOT)/src/MRTests/MRTests-Prefix.pch",
                ]
            )
        ),
    ]
)
